### ISSUE TITLE
Distributing sources on npm instead of transpiled bundle

### ISSUE THREAD

**Issue by 19majkel94** [IRCraziestTaxi/typeorm-linq-repository#11]
Why you publish sources on npm? You should do compile with declarations emiting and then upload the transpiled files, not sources. Now my tsc complain about files to compile outside of `rootDir` directory. Look how it's done in typeorm and other pleerock libraries.

**Comment by 19majkel94** [comment]
And by the way - where is your tsconfig.json file? Why you have it locally instead of pushed onto git?

**Comment by IRCraziestTaxi** [comment]
@19majkel94 You are absolutely right; I should have published compiled scripts with type definitions. I realized that as soon as TypeScript updated and introduced breaking changes to my code.

I assume the issue you are having deals with the stricter generic type checks recently introduced in TypeScript. I have published an updated build for that (@0.0.4); see if that fixes your problem.

Going forward, I am definitely going to start publishing compiled code rather than the source.

Let me know if the updated build fixes your problem.

(Also note that, right now, this package only works with typeorm@0.1.0-alpha.10; I am working on upgrading it to work with the latest alpha.)

**Comment by 19majkel94** [comment]
I have problem with compiling my app - I have excluded `node_modules` so it transpile only my app code, not the 3rd party libraries. I've done it manually (both `typeorm-linq-repository` and `ts-simple-nameof`) and now it works. Good work BTW! ;)

So please add tsconfig.json to the repo, configure building script and upload on npm the compiled with declarations version (*.js and *.d.ts) on all your npm packages.

**Comment by IRCraziestTaxi** [comment]
Excellent. I'm glad you got it working! :)

I will leave this issue open until the proper files are published rather than raw source with not tsconfig.

**Comment by 19majkel94** [comment]
You can see how I've done it in my lib:
https://github.com/19majkel94/class-transformer-validator

All sources are in `src` folder (even index.ts), tsconfig with `outDir` and `rootDir` options, so genereated build is in `build` - you only have to copy readme, licence and package.json to this folder (maybe as a gulp publish task?) to publish it. package.json `private: true` helps with incidental publish all repo content 😉

**Comment by IRCraziestTaxi** [comment]
Fixed in v0.1.0!

**Comment by IRCraziestTaxi** [comment]
Or, rather, 0.1.1. Had to make an update due to a dependency needing to be updated as well.
