### ISSUE TITLE
Unable to use package with typeorm 0.3.10

### ISSUE THREAD

**Issue by AlexBrunGiglio** [IRCraziestTaxi/typeorm-linq-repository#221]
Hello,
I would like to migrate a nestjs project to its latest version (v9). I already use your package which is amazing but when I wanted to install it, the version of typeorm used by nestjs is too high compared to the package.

Would it be possible to update these dependencies?

nestjs package.json : 
```json
 "dependencies": {
    "@nestjs-modules/mailer": "^1.8.1",
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/jwt": "^9.0.0",
    "@nestjs/passport": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/schedule": "^2.1.0",
    "@nestjs/swagger": "^6.1.2",
    "@nestjs/typeorm": "^9.0.1",
    "bcrypt": "^5.1.0",
    "bcryptjs": "^2.4.3",
    "jsonwebtoken": "^8.5.1",
    "linqts": "^1.14.4",
    "passport": "^0.6.0",
    "passport-jwt": "^4.0.0",
    "passport-local": "^1.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
```

error : 
```sh
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: nest-start@0.0.1
npm ERR! Found: typeorm@0.3.10
npm ERR! node_modules/typeorm
npm ERR!   peer typeorm@"^0.3.0" from @nestjs/typeorm@9.0.1
npm ERR!   node_modules/@nestjs/typeorm
npm ERR!     @nestjs/typeorm@"^9.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! typeorm-linq-repository@"*" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: typeorm@0.2.45
npm ERR! node_modules/typeorm
npm ERR!   peer typeorm@"^0.2.34" from typeorm-linq-repository@1.1.3
npm ERR!   node_modules/typeorm-linq-repository
npm ERR!     typeorm-linq-repository@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by IRCraziestTaxi** [comment]
@AlexBrunGiglio Thanks for bringing this up. I just published version 2.0.0, which uses the latest version of TypeORM. It took me a little longer than I expected because TypeORM introduced breaking changes (currently deprecated, but soon to be removed) that changed the way `LinqRepository` is constructed.

Summary directly from my updated readme:

Due to [breaking changes in TypeORM](https://github.com/typeorm/typeorm/issues/7428), namely the removal of `getConnectionManager`, the constructor for `LinqRepository` now requires the TypeORM `DataSource` in addition to the entity model. Likewise, since individually managed `DataSource` objects replace the `ConnectionManager` paradigm, `RepositoryOptions` now no longer contains the `connectionName` property.

Therefore, `new LinqRepository(entity)` is now `new LinqRepository(dataSource, entity)`.

I personally feel they screwed the pooch on the removal of the `ConnectionManager` paradigm, but anyway, upgrade this lib to 2.0.0 to be able to use the latest version of TypeORM.
