### ISSUE TITLE
Integration with typeorm entity schemas

### ISSUE THREAD

**Issue by irissoftworks** [IRCraziestTaxi/typeorm-linq-repository#61]
Was playing with things and realized the following:

```
import { MatrixSchema } from '@domain/matrix/matrix.entity';
import { EntitySchema, getRepository } from 'typeorm';
import { baseEntitySchema } from './base.schema';
import { LinqRepository } from 'typeorm-linq-repository';

export const matrixEntitySchema = new EntitySchema<MatrixSchema>({
  name: 'matrix',
  columns: {
    ...baseEntitySchema,
    realm: {
      type: 'string',
      length: 100,
    },
  },
});

const b = getRepository(matrixEntitySchema);

const d = new LinqRepository(matrixEntitySchema); // doesn't compile
```

Looks like it's just a typing issue ?

**Comment by IRCraziestTaxi** [comment]
I am unfamiliar with this `EntitySchema` business, but after looking at the code in both TypeORM and typeorm-linq-repository, I don't see why it would be presenting a problem. I'll look into it when I get some time.

**Comment by IRCraziestTaxi** [comment]
Ok... I see. `LinqRepository` expects a constructor of an entity, so since `matrixEntitySchema` is an instance of an `EntitySchema` rather than the type of a class, it throws the error.

It appears that simply having `LinqRepository` accept either a class constructor of type `T` _or_ an `EntitySchema<T>` will allow Entity Schemas to be used.

I'll update as soon as possible.

**Comment by IRCraziestTaxi** [comment]
Fixed in `typeorm-linq-repository@alpha.19`.
