### ISSUE TITLE
Add support for groupBy

### ISSUE THREAD

**Issue by bengry** [IRCraziestTaxi/typeorm-linq-repository#65]
I tested out the library in one of our projects, and it seems great, much easier then the built-in QueryBuilder in TypeORM, in addition to being more type-safe.

I did notice that there's no groupBy operator, is there a technical reason behind it, or is it just not implemented at the moment (if that's the case - is there any work being done on it?)

Thanks.

**Comment by IRCraziestTaxi** [comment]
Hey, thanks for using the lib!

I knew this issue was coming sooner than later. There is currently no work being done on it of which I am aware. I have been meaning to implement it, but I haven't had the time to fool around with it. I have not even used TypeORM's groupBy, so I will need to try it out and see what needs to be done on my side to make it work with this lib.

I should be able to look at it soon. I will keep you posted.

**Comment by IRCraziestTaxi** [comment]
Update - I got a second to check out TypeORM's own `groupBy` method and realized it isn't as complicated as I assumed it would be. I'm used to Entity Framework's `GroupBy` method resulting in an `IGrouping` result that separates the grouped entities and I assumed TypeORM would do something similar, but that does not appear to be the case as the results are still just an array of the entity type. `groupBy` should be trivial to add in this lib and I should have some time in the next day or two to implement it. I'll keep you posted.

**Comment by IRCraziestTaxi** [comment]
fixed in version 1.0.0-alpha.21 via #66.
