### ISSUE TITLE
Use for NestJs

### ISSUE THREAD

**Issue by longpro1601** [IRCraziestTaxi/typeorm-linq-repository#67]
Hi,
I'm using NestJs,
I need add and config typeorm-linq-repository  for project

Please help me @IRCraziestTaxi .

Thanks.

**Comment by IRCraziestTaxi** [comment]
Hi @longpro1601, I appreciate your interest in using this library!

The beauty of this library is that all it does is wrap TypeORM's connection (configured at app startup) to expose the repository, so the configuration portion of the work is more on the TypeORM side than the typeorm-linq-repository side.

While I have never used NestJS, I took a quick look at their documentation and they actually have [a page dedicated to setting up TypeORM](https://docs.nestjs.com/recipes/sql-typeorm), so you can use that to set up the TypeORM side of things.

**However**, stop at the end of the "Getting started" section of that page (after they create `database.module.ts`). Do not continue to their "Repository pattern" section.

Instead, all you need to do to use typeorm-linq-repository is import `LinqRepository` and construct it wherever needed.

For instance:

```ts
import { LinqRepository } from "typeorm-linq-repository";
import { User } from "../path/to/entities/User";

// ...

async function getUserByEmail(email: string): User {
    const user = await new LinqRepository(User);

    return user;
}

// ...
```

If you have any further questions about the configuration side of things, continue to reference NestJS's docs and the TypeORM documentation as well.

If you have any further questions about using this library, the readme has pretty much everything you need to know about it.

If you run into something that is not clear, however, I will be glad to help. Also let me know if a part of the readme needs clarification to make it easier to use.

Feel free to close this issue if I have answered your questions enough to get you up and running. Otherwise I will check back in a few days or so to see if it can be closed.

**Comment by welkie** [comment]
@IRCraziestTaxi Awesome example. I suggest copying those instructions into the repo readme.

**Comment by IRCraziestTaxi** [comment]
Going to go ahead and close this since there hasn't been any activity for a while and the original question seems to have been addressed. I will indeed beef up the readme with more useful examples such as those above when I have some time.
