### ISSUE TITLE
How to handle nullable relations

### ISSUE THREAD

**Issue by dotslashx** [IRCraziestTaxi/typeorm-linq-repository#74]
What is the correct way to handle nullable relations using this library?
I cant find anything about this situation in the docs.

For example we have:
```ts
@Entity('foo')
class Foo {
    @PrimaryGeneratedColumn('uuid')
    public id!: string;

    @ManyToOne(() => Bar, bar => bar.id, {nullable: true})
    public bar!: Bar | null;
}

@Entity('bar')
class Bar {
    @PrimaryGeneratedColumn('uuid')
    public id!: string;

    @ManyToOne(() => Baz, baz => baz.id)
    public baz!: Baz;
}

@Entity('baz')
class Baz {
    @PrimaryGeneratedColumn('uuid')
    public id!: string;

    @Column()
    public something!: string;
}
```

However I am unable to load the `Foo` object along with the `Bar` and `Baz` relations:

```ts
const fooRepository = new LinqRepository(Foo, {autoGenerateId: true});

fooRepository
    .getById('a9a88deb-5b0c-4583-ab85-62cfa8997aaa')
    .include(foo => foo.bar)
    .thenInclude(bar => bar.baz); // <----- This one yelds an error - bar may be null
```

Is there any solution for this?

**EDIT:**
It turns out its caused by `strictNullChecks` setting of `tsconfig`.
Will this be supported?

**Comment by IRCraziestTaxi** [comment]
Hey @dotslashx, thanks for using the repo!

Can you check and share your installed versions of `typescript` and `typeorm-linq-repository`?

With the below code, I am getting no errors at neither compile time nor run time.

```ts
// Foo.ts
import { Entity, ManyToOne, PrimaryGeneratedColumn } from "typeorm";
import { Bar } from "./Bar";

@Entity()
export class Foo {
    @PrimaryGeneratedColumn("uuid")
    public id!: string;

    @ManyToOne(() => Bar, bar => bar.id, { nullable: true })
    public bar!: Bar | null;
}

// Bar.ts
import { Entity, ManyToOne, PrimaryGeneratedColumn } from "typeorm";
import { Baz } from "./Baz";

@Entity()
export class Bar {
    @PrimaryGeneratedColumn("uuid")
    public id!: string;

    @ManyToOne(() => Baz, baz => baz.id)
    public baz!: Baz;
}

// Baz.ts
import { Column, Entity, PrimaryGeneratedColumn } from "typeorm";

@Entity()
export class Baz {
    @PrimaryGeneratedColumn("uuid")
    public id!: string;

    @Column()
    public something!: string;
}

// index.ts
import { createConnection } from "typeorm";
import { LinqRepository } from "typeorm-linq-repository";
import { Foo } from "./src/entities/Foo";

async function main(): Promise<void> {
    const fooRepository = new LinqRepository(Foo);

    const targetFoo = await fooRepository
        .getById("a9a88deb-5b0c-4583-ab85-62cfa8997aaa")
        .include(foo => foo.bar)
        .thenInclude(bar => bar.baz);

    console.log("Done!");
}

createConnection()
    .then(async connection => {
        await main();

        connection.close();
    });
```

Here are the versions of my installed dependencies:

```
  "dependencies": {
    "mysql": "^2.17.1",
    "typeorm": "^0.2.19",
    "typeorm-linq-repository": "^1.0.0-alpha.23"
  },
  "devDependencies": {
    "@types/node": "^12.7.5",
    "tslint": "^5.20.0",
    "typescript": "^3.6.3"
  }
```

**Comment by dotslashx** [comment]
Hello @IRCraziestTaxi 

I am using the exact same versions, but I've looked into it and turns out to be the `tsconfig` options that I am using, precisely the `strictNullChecks` which is also enabled by `strict`. I would really like to keep that option enabled. Is this possible for this library to support it?

**Comment by IRCraziestTaxi** [comment]
@dotslashx Ok, I placed `"strictNullChecks": true` in my tsconfig and that checks out.

However, the source of the error is not typeorm-linq-repository, but typescript itself.

Consider the following:

```ts
function callbackTest<T, R>(callback: (obj: T) => R): void {
}

// Error: Object is possibly 'null'.
callbackTest<Foo, Baz>(foo => foo.bar.baz);
```

Just like the callback passed to `callbackTest` that returns `foo.bar.baz`, typescript treats the lambda you pass to typeorm-linq-repository methods as it would any other callback.

If I remove `| null` from `public bar!: Bar | null;` so that it becomes `public bar!: Bar;`, the error goes away.

I was actually wondering why your type annotation for `bar` was `Bar | null` rather than just `Bar`. Out of curiosity, does it provide any benefits you specifically seek? My suggestion would be to remove that if possible.

At any rate, I'm going to go ahead and close this issue as it is a typescript problem altogether.

**Comment by IRCraziestTaxi** [comment]
@dotslashx Ok, so out of curiosity I changed the definition of `Foo.bar` to `public bar?: Bar;` and the error turned into `Object may be 'undefined'.`

I did find that if I change `.thenInclude(bar => bar.baz)` to `.thenInclude(bar => bar!.baz)`, the error goes away, but doing that would cause errors in typeorm-linq-repository based on how it parses the lambda to get the property names.

I am going to reopen this issue because I think it may be reasonable to have either typeorm-linq-repository or its dependency, ts-simple-nameof, remove instances of `!` and `?` from stringified lambdas as neither of those characters is valid in a property name anyway.

I will let you know what I decide to do with it.

**Comment by dotslashx** [comment]
This is actually interesting, I am looking forward for your decision.

To answer your question, I am using the null type hint to be able to reset the relation as it is nullable and the strict mode will not let me do it without the null type. On the other hand the strict null checks simply helps me to find most of compile time mistakes when using properties of object which may be null or undefined which I really appreciate.

**Comment by IRCraziestTaxi** [comment]
@dotslashx I updated `ts-simple-nameof` to strip `!` operators from the lambdas passed to this lib's methods, so you can now safely use `.thenInclude(bar => bar!.baz)`. Just update `typeorm-linq-repository` to the latest (`1.0.0` - finally decided to let it graduate from alpha) and you should be good to go! 

Thanks for helping find this problem! I'm certain others have had or will have the same problem.
