### ISSUE TITLE
getOne() method looks not LIMIT query 

### ISSUE THREAD

**Issue by freefred81** [IRCraziestTaxi/typeorm-linq-repository#76]
Hi .. again here.

I'm using your lib and it's great!!.. but just one quick doubt ...

I'm doing a query like:

```
 const query = await this._accountRepository
            .getOne()
            .where(xx => xx.sfid)
            .isNotNull();
```

Not it works and return a single object ... BUT if i enable the logs of the query .. i can see this:
`
 SELECT "entity"."lastname" AS "entity_lastname", "entity"."attivo__c" AS "entity_attivo__c", "entity"."personhasoptedoutofemail" AS "entity_personhasoptedoutofemail", "entity"."id_account_18__c" AS "entity_id_account_18__c", "entity"."sesso__c" AS "entity_sesso__c", "entity"."personcontactid" AS "entity_personcontactid", "entity"."recordtypeid" AS "entity_recordtypeid", "entity"."consenso_marketing__c" AS "entity_consenso_marketing__c", "entity"."personemail" AS "entity_personemail", "entity"."codice_fiscale__c" AS "entity_codice_fiscale__c", "entity"."consenso_marketing_email__c" AS "entity_consenso_marketing_email__c", "entity"."consenso_marketing_tel__c" AS "entity_consenso_marketing_tel__c", "entity"."name" AS "entity_name", "entity"."stato_commerciale__c" AS "entity_stato_commerciale__c", "entity"."prossimo_compleanno__c" AS "entity_prossimo_compleanno__c", "entity"."consenso_marketing_sms__c" AS "entity_consenso_marketing_sms__c", "entity"."has_whatsapp__c" AS "entity_has_whatsapp__c", "entity"."phone" AS "entity_phone", "entity"."altra_email__c" AS "entity_altra_email__c", "entity"."ownerid" AS "entity_ownerid", "entity"."ispersonaccount" AS "entity_ispersonaccount", "entity"."isdeleted" AS "entity_isdeleted", "entity"."data_scadenza_consenso_mktg__c" AS "entity_data_scadenza_consenso_mktg__c", "entity"."systemmodstamp" AS "entity_systemmodstamp", "entity"."persondonotcall" AS "entity_persondonotcall", "entity"."eta__c" AS "entity_eta__c", "entity"."alert_truffa__c" AS "entity_alert_truffa__c", "entity"."createddate" AS "entity_createddate", "entity"."personmobilephone" AS "entity_personmobilephone", "entity"."personbirthdate" AS "entity_personbirthdate", "entity"."salutation" AS "entity_salutation", "entity"."professione__c" AS "entity_professione__c", "entity"."tipo_db__c" AS "entity_tipo_db__c", "entity"."personhomephone" AS "entity_personhomephone", "entity"."firstname" AS "entity_firstname", "entity"."consenso_trattamento_dati__c" AS "entity_consenso_trattamento_dati__c", "entity"."id_anagrafica__c" AS "entity_id_anagrafica__c", "entity"."sfid" AS "entity_sfid", "entity"."id" AS "entity_id", "entity"."_hc_lastop" AS "entity__hc_lastop", "entity"."_hc_err" AS "entity__hc_err", "entity"."id_contatto_18__pc" AS "entity_id_contatto_18__pc" FROM "salesforce"."account" "entity" WHERE "entity"."sfid" IS NOT NULL`

As you can see the select query looks like NOT be LIMITED to one record .. (for example having LIMIT 1 at the end ) .. so i ask if is possible that the limit is done in the memory ONCE the query as been hitted on the DB and has returned all records  

Really thnx!!!

**Comment by IRCraziestTaxi** [comment]
Hello again!

Huh... that is interesting. `typeorm-linq-repository`'s `getOne` method literally calls `typeorm`'s `getOne` method under the hood, so I would expect that the query is limited to one result.

I would suggest getting a standard `typeorm` repository (either with its `getRepository` method or, since version `1.0.0` of `typeorm-linq-repository`, you can use `LinqRepository`'s `typeormRepository` property to get it) and perform a query using its own `getOne` method and see if the query is the same. It should be since `typeorm-linq-repository` calls that method to get the result.

If the query is the same (with no `LIMIT`), I would suggest opening an issue with TypeORM (assuming one does not already exist).

If `typeorm`'s `getOne` method _does_ correctly form the query with a `LIMIT`, then I will investigate my code to see why that `LIMIT` would be lost despite calling the same method.

Thanks again for continuing to use the repo!

**Comment by freefred81** [comment]
HI!!...as every time..really thnx for you time and your reply!!... I'm realy enjoy using your repo.

Ok i'll do as you said ... (for the moment i put maybe a take(1) at the and).

Another quick question .. i notice if i do a query like:


```
 const query = await this._TaskRepository
        .getAll()
        .include(u => u.account)
        .orderByDescending(xx => xx.id, { nullsFirst: false })
        .take(10)
        ;
```

and it works as expected .. it retive 10 task with related account (relation many-to-one)

BUT if i do a join like:


 const query = await this._TaskRepository
        .getAll()
        .join(u => u.account)
        .orderByDescending(xx => xx.id, { nullsFirst: false })
        .take(10)
        ;

it works .. return the 10 task..but the property account .. inside taskj ..is EMPTY .. maybe do i not understood well as join works? .. do it also a projection of the related entity inside ?

Best regards and really thnx for your effort to maintain the repo ..

**Comment by IRCraziestTaxi** [comment]
@freefred81 To answer that question about `include` versus `join`:

* `include` performs a `LEFT JOIN` and `SELECT` on the included entity, which is why you get the `account` with each `Task` in the results.

* `join` performs an `INNER JOIN` rather than a `LEFT JOIN` and also performs *NO* `SELECT`, so that is why `account` is not included with the `Task`. Also, since `join` performs an `INNER JOIN`, for some relationships, results may be lost; `joinAlso` performs a `LEFT JOIN` (again, with *NO* `SELECT`).

So, in short:

* `include`: `LEFT JOIN` and `SELECT`
* `join`: `INNER JOIN`
* `joinAlso`: `LEFT JOIN`

`join` and `joinAlso` should only be used for filtering results based on the conditions of relationships. If you need to include the relationships, you must use `include`. Therefore, up to version `1.0.0`, it was actually not possible to filter results with an `INNER JOIN` while including the relationships because it ignored duplicate join aliases altogether, so using a `join` after an `include` did nothing except add join conditions to the `LEFT JOIN` set by `include`.

However, as of version `1.0.1`, which I released last night, it is possible to include relationships while also filtering with an `INNER JOIN` rather than a `LEFT JOIN`! See *Filtering Included Relations* in the readme for info on that. It's not extremely intuitive, but it works out fairly easily without breaking previous behavior.

Sorry if all this is confusing. This is a pretty complex library. Everything you need to know about joins and includes is in the readme, which I know is very long and frustrating to navigate. I plan to create an .io site for this library's docs if I can ever find the time...

Let me know if that clears it up for you.

**Comment by freefred81** [comment]
YEs .. it's very clear now .. and the lib is not so complicated  .... i know do a ORM linq style (like EF) i's not so easy ..and you do a GREAT job.... really thnx for your time and explanation!!

**Comment by ljobse** [comment]
I think this could be a TypeORM log issue. Whenever you specify take() this will not show a limit in the logs. So that means 1 of 2 things:
1.- TypeORM logs are incorrect
2.- TypeORM handles limits in memory. If this is the case, the package would not be usable for any production application so I highly doubt that.

**Comment by IRCraziestTaxi** [comment]
Terribly sorry for the long period of inactivity on this.

I agree with @ljobse - this seems like a problem on TypeORM's end in one way or another. I'm going to go ahead and close this one.
