### ISSUE TITLE
Cannot SELECT column1, column2, ... FROM table_name;

### ISSUE THREAD

**Issue by longpro1601** [IRCraziestTaxi/typeorm-linq-repository#81]
Hi,
I cannot SELECT code, ... FROM table_name;

 const result = await this.companyRepository.getAll().select(x=>x.code);
as a result:     SELECT *  FROM table_name;

Please help me for SELECT column1, column2, ...;

Thanks

**Comment by IRCraziestTaxi** [comment]
Hey @longpro1601,

Since this lib was built around objects and type safety, I never considered selecting only specific columns from a table. It was meant to query objects with type safety in mind and return a known type: the type of the object tied to the table being queried. Right off the top of my head, I cannot envision a way to make the return type of the object containing the selected properties known.

The intended purpose of the `select` method in this lib is to select a property to project from an inner query to an `inSelected` or `notInSelected` method, as demonstrated in [this portion of the readme](https://github.com/IRCraziestTaxi/typeorm-linq-repository#including-or-excluding-results-within-an-inner-query). It was not implemented with selecting multiple columns in mind.

That being said, I can put this on the back burner and take a look into a possible implementation for this functionality after I get some time to squash some other issues that are open in this lib. Unfortunately, I don't see as much value in this feature as I do some other issues that are open.

As always, thanks for using the lib and letting me know where features are needed!

P.S. In the meantime, it is possible to perform the type of `select` you wish to perform by using the `QueryBuilder` of the underlying `typeormRepository` of the `LinqRepository`.

**Comment by darrenprunty** [comment]
It would be unreal if this was possible! I know it's closed a while now though. 

Just coming from working with Entity Framework to a project using TypeOrm and NestJs. The default querybuilder is scary that everything is hard-coded as string.
