### ISSUE TITLE
LOWER called on non string columns when using .where().equal() resulting in a database error. 

### ISSUE THREAD

**Issue by ivanjd** [IRCraziestTaxi/typeorm-linq-repository#85]
When performing the following query
```
const products = await this.productRepo.getAll()
.where(p => p.categoryId)
.equal(catId);
```
the executel SQL looks like that:
` SELECT ... FROM "public"."product" "entity" WHERE LOWER("entity"."categoryId") = '1'` and postgres responds with `error: function lower(integer) does not exist`
A workaround it to use `.equal(catId, {matchCase: true})`, however having to do this in a number of places is annoying. 

`categoryId` is defined as a number in the model and the variable `catId` passed to `.equal()` is also type number . The same thing happens in similar queries for other entities too.

**Comment by ivanjd** [comment]
Turns out it is not a problem with the library. NestJS controller parameters have a wrong runtime type. In a controller method that looks like this:
``` async getReviews(@Param('productId') productId: number) {...}```
the runtime type of `productId` is string regardles of the fact that it is defined as number and this problem leaks all the way down to the `typeorm-linq-repository` code that generates the query. Any suggestions on how to overcome that?

**Comment by IRCraziestTaxi** [comment]
That is odd. I am glad you brought the nest route parameter issue to my attention... I took for granted if you typed it as a number it would parse it as a number. That should definitely be opened as an issue on nest, assuming it has not already been.

I suppose the most straightforward workaround would be to use `parseInt()` on all route IDs. Hopefully nest will fix the number issue.

Interestingly, I have not run into this issue with using `.where(x => x.id).equal(id)` even when the ID was a string because I forgot to use `parseInt()` on the ID from the request params in a guard, but I am using MySQL rather than Postgres.

Since this is not an issue with the lib, I will go ahead and close this issue, but feel free to continue the discussion.

**Comment by ivanjd** [comment]
We ended up creating a custom @Param attribute for that and I posted a question in nest.
I have another similar issue now. It has to do with enums.
```
issueRepo.getAll()
.where(i => i.status)
.equal(IssueStatus.Pending, {matchCase: true});
```
If I don't specify  {matchCase: true} the lib tries to call LOWER on the enum and pg throws an error. The enum is defined as follows:
```
export enum IssueStatus{
  Pending = 'pending',
  Closed = 'closed',
  ...
}
```
And the property in the entity definition is decorated like that:
```
@Column({ type: 'enum', enum: IssueStatus})
```

**Comment by IRCraziestTaxi** [comment]
That is strange... if the enum value is just a string, then there should not be a problem. I will debug and see what is going on.

**Comment by IRCraziestTaxi** [comment]
Sorry, I did not really pay attention to your column definition when I first replied. I will also say that I have never used a column type of "enum" so I am not really sure what the implications are in Postgres or any other DB engine. Since specifying `{ matchCase: true }` in your query fixes it, I assume calling `LOWER` on enum columns just isn't valid despite the fact that at the end of the day they are strings.

Unfortunately, the lib has no way of knowing whether an enum value that is a string is an enum or not since just the string value is passed to the `equal` function. There may be some way to see what the type of the column on the class being queried is, but even then that could only be performed on the class that is the base type of the query.

If you want to open a separate issue for it (because in my mind this is a separate issue), when I get some time to look at it I will see what I can do with it.
